"""State definitions for the SQL copilot graph."""

from __future__ import annotations

from typing import Any, TypedDict

from sql_copilot.tools.database import QueryResult


class SQLAgentState(TypedDict, total=False):
    """Mutable state passed between LangGraph nodes."""

    question: str # User question in natural language
    schema_overview: str # A textual overview of the database schema
    generated_sql: str # The SQL query generated by the SQLGeneratorNode
    validated_sql: str # The SQL query after validation (could be the same as generated_sql or modified for safety)
    sql_validation_error: str | None # Error message if SQL validation fails
    query_result: QueryResult # The result of executing the SQL query
    execution_error: str | None # Error message if query execution fails
    analysis: str # Analysis of the query result
    metadata: dict[str, Any] # Additional metadata related to the query and its execution
