"""State definitions for the SQL copilot graph."""

from __future__ import annotations

from typing import Any, TypedDict

from tools.database import QueryResult


class SQLAgentState(TypedDict, total=False):
    """Mutable state passed between LangGraph nodes."""

    question: str # User question in natural language
    selected_database: str # Database name selected for the question
    schema_overview: str # A textual overview of the database schema
    intent: str | None # User intention (query or modification)
    intent_error: str | None # Error message if intent classification fails
    generated_sql: str # The SQL query generated by the SQLGeneratorNode
    validated_sql: str # The SQL query after validation (could be the same as generated_sql or modified for safety)
    sql_validation_error: str | None # Error message if SQL validation fails
    query_result: QueryResult # The result of executing the SQL query
    execution_error: str | None # Error message if query execution fails
    analysis: str # Analysis of the query result
    metadata: dict[str, Any] # Additional metadata related to the query and its execution
    user_role: str # Role of the authenticated user
    is_authorized: bool # Whether the user has authorization to proceed
    authorization_error: str | None # Error message if authorization fails
    needs_confirmation: bool # Whether user confirmation is required before execution
    execution_requested: bool # Whether execution is pending user confirmation
    execution_confirmed: bool # Whether user has confirmed execution
    thread_id: str # Thread identifier used to resume an interrupted graph
    interrupt: dict[str, Any] # Serialized LangGraph interrupt payload
